const GOOGLE_COOKIE_ALLOWLIST = new Set([
  'SID',
  'HSID',
  'SSID',
  'APISID',
  'SAPISID',
  'LOGIN_INFO',
  'CONSENT',
  'SOCS',
  'NID',
  'AEC',
  '__Secure-1PSID',
  '__Secure-3PSID',
  '__Secure-1PAPISID',
  '__Secure-3PAPISID',
  '__Secure-1PSIDTS',
  '__Secure-3PSIDTS',
  '__Secure-1PSIDCC',
  '__Secure-3PSIDCC',
  '__Secure-ENID',
]);

export function shouldSendCookie(cookie) {
  if (!cookie || !cookie.name || cookie.value == null) return false;
  const isGoogleDomain = cookie.domain === 'google.com' || cookie.domain.endsWith('.google.com');
  if (isGoogleDomain) {
    return GOOGLE_COOKIE_ALLOWLIST.has(cookie.name) || cookie.name.startsWith('__Secure-');
  }
  return true;
}

export function dedupeCookies(cookies) {
  const map = new Map();
  for (const cookie of cookies) {
    if (!shouldSendCookie(cookie)) continue;
    map.set(`${cookie.domain}\t${cookie.path}\t${cookie.name}`, cookie);
  }
  return [...map.values()];
}

function sanitize(value) {
  return String(value == null ? '' : value).replace(/[\t\r\n]/g, ' ');
}

export function toNetscape(cookies) {
  const lines = ['# Netscape HTTP Cookie File', '# Generated by Video Download Manager extension', ''];

  for (const cookie of cookies) {
    if (!shouldSendCookie(cookie)) continue;
    const domain = cookie.httpOnly ? `#HttpOnly_${cookie.domain}` : cookie.domain;
    const includeSubdomains = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const cookiePath = cookie.path || '/';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expires = cookie.session || !cookie.expirationDate ? '0' : String(Math.floor(cookie.expirationDate));
    lines.push(
      [domain, includeSubdomains, cookiePath, secure, expires, sanitize(cookie.name), sanitize(cookie.value)].join('\t'),
    );
  }

  return `${lines.join('\n')}\n`;
}
